### ISSUE TITLE
这个部署在自己服务器上面可以使用吗

### ISSUE THREAD

**Issue by kanyou** [onewayticket255/pixivtoken#1]
请问下这个是直接部署在服务器然后使用node main.js，然后把以前脚本里的let url替换成自己的地址就可以使用了吗

**Comment by kanyou** [comment]
还有这个是需要自己有一个已经是会员账户的基础上才可以使用是吗

**Comment by onewayticket255** [comment]
是的.
我对官方app质量非常不满意, 所以不再使用官方app和不再提供会员token.
推荐一个客户端: https://apps.apple.com/cn/app/p%E7%AB%99%E5%8A%A9%E6%89%8B-%E7%B2%BE%E7%BE%8E%E4%BA%8C%E6%AC%A1%E5%85%83%E5%A3%81%E7%BA%B8%E9%87%87%E9%9B%86%E5%B7%A5%E5%85%B7/id1161125462?l=en
